# Generated by Django 4.2.7 on 2023-12-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='name_branch',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='name_faculty',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_project',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name_student',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name_teacher',
            new_name='fullname',
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='id_project')),
            ],
        ),
    ]
