# Generated by Django 4.2.7 on 2023-12-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_branch_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='files',
            new_name='file',
        ),
    ]
